### ISSUE TITLE
3rd part plugins?

### ISSUE THREAD

**Issue by bcomnes** [ionutvmi/sublime-jsfmt#21]
Can I load in plugins that are not included with the sublime somehow?  Install them with `-g`?

**Comment by ionutvmi** [comment]
Yes you can, you don't need to install them globally.
1. Go to the packages folder (Preferences -> Browse Packages)
2. cd into the `jsfmt` folder.
3. Install the plugins you need.
4. Go to your jsfmt settings file and add the name of the plugin in the `plugins` array.

**Comment by ionutvmi** [comment]
I also added this steps in the readme file for future reference.
Please let me know if you encounter any problem in this process.

**Comment by ionutvmi** [comment]
any update here ?

**Comment by bcomnes** [comment]
Ack this fell of my radar.  

Yeah that totally works.  It would be neat (and more convenient) if we could access global node_modules, but this works for now.
