### ISSUE TITLE
Disable format selected text

### ISSUE THREAD

**Issue by santimacia** [ionutvmi/sublime-jsfmt#22]
I use the autoformat on save, but I have problems if I have something selected because it formats what is selected and not the whole document.

It's possible to desactivate?

**Comment by ionutvmi** [comment]
We don't have an option for it at the moment but I do think it would help to have one.
I will add it with the first chance I get.

**Comment by ionutvmi** [comment]
I have released this option in 1.0.6, it should be on package control in a few hours.
Please let me know if everything is ok for you and close this issue.

**Comment by santimacia** [comment]
awesome :smiley:
