### ISSUE TITLE
Can't change from singlequoted to doublequoted

### ISSUE THREAD

**Issue by 0x4139** [ionutvmi/sublime-jsfmt#24]
i am not able to change for example from `'use strict'` to `"use strict"` using the formatter even if i activated the plugin and everything.

**Comment by ionutvmi** [comment]
I just tested on my PC and it seems to work fine.

Make sure your settings look similar to this:
```js
{
    "autoformat": false,
    "options":
    {
        "indent":
        {
            "value": "    "
        },
        "plugins":
        [
            "esformatter-quotes"
        ],
        "quotes":
        {
            "type": "double"
        }
    }
}

```

If it still doesn't work please post more details about your system: your OS, sublime text version, and your settings.

**Comment by 0x4139** [comment]
Thanks, it seems i wasn't containing them in "options", any tips on how to make this work for *.jsx files?

**Comment by ionutvmi** [comment]
we have a settings for enabling custom extensions for autoformat
```js
    // array of extensions for autoformat
    "extensions": ["js", "sublime-settings"],
```
you can find more info about all the available options in the [readme](README.md) file
