### ISSUE TITLE
Additional tab gets inserted when developing with angular

### ISSUE THREAD

**Issue by leonklingele** [ionutvmi/sublime-jsfmt#25]
This:

    angular
    	.module('myApp')
    	.controller('MainCtrl', ['$scope', function($scope) {
    		var test; // <-- Notice: Additional tab will get inserted here
    	}]);

is formatted to this:

    angular
    	.module('myApp')
    	.controller('MainCtrl', ['$scope', function($scope) {
    			var test; // <-- Notice: Additional tab has been inserted here
    	}]);

## What I expect
Line with `var test;` should not be indented with two more tabs than the previous line.

My `jsfmt.sublime-settings`:

```
{
	"alert-errors": true,
	"autoformat": true,
	"extensions":
	[
		"js"
	],
	"node-path": "node",
	"options":
	{
		"indent":
		{
			"value": "	"
		},
		"plugins":
		[
		],
		"preset": "jquery"
	},
	"options-JSON":
	{
		"plugins":
		[
			"esformatter-quotes"
		],
		"quotes":
		{
			"type": "double"
		}
	}
}
```

**Comment by leonklingele** [comment]
Solved by running `npm update`.
Please update the packaged node modules.

**Comment by ionutvmi** [comment]
Hi,
thank you for reporting this I will update all default the packages now.

**Comment by ionutvmi** [comment]
It appears that v0.4.1 has a small problem for formatting json files witch I reported [here](https://github.com/rdio/jsfmt/issues/144)
I will delay the update here for a day or two to see if I get any feedback on that bug.

**Comment by ionutvmi** [comment]
jsfmt was updated

**Comment by leonklingele** [comment]
Thank you :smile_cat:
