### ISSUE TITLE
File does not anchor at current line on save

### ISSUE THREAD

**Issue by captain-torche** [ionutvmi/sublime-jsfmt#28]
When I'm saving a file, the current display goes back to the first line.
Line bookmarks are also suppressed (Or rather put to the last line of the file).

**Comment by ionutvmi** [comment]
Can you give more details about your environment and maybe some example dummy code ?
For me sublime tries to keep the cursor in a similar position and depending on the changes that were done after the formatting it might get some offset but it never throws me to the fist line of the file.
Same for the bookmarks they usually get an offset. [demo gif](http://i.imgur.com/Fys0RZ7.gif)

**Comment by timmipetit** [comment]
I'm having exactly the same problem, even with a minimal 2-line file. I'm using Sublime 2.0.2
small video of the problem: http://webms.org/w/pQzK92Nx/

**Comment by ionutvmi** [comment]
I just updated all the packages to the latest version.

Can you tell me if this is still reproducing ?

**Comment by timmipetit** [comment]
I just updated to 1.0.8, but unfortunately the problem still exists.

**Comment by timmipetit** [comment]
I switched to Sublime 3, and haven't been able to reproduce this issue since then.
