### ISSUE TITLE
ES7 decorator throwing error

### ISSUE THREAD

**Issue by rkhayat** [ionutvmi/sublime-jsfmt#33]
Hello, I am using radium, including it as a decorator outside my class
@Radium

jsfmt yells at me everytime I save, and doesn't format.

**Comment by ionutvmi** [comment]
You should open this issue in the (rdio/jsfmt)[https://github.com/rdio/jsfmt/issues] repo.
This sublime text plugin only uses jsfmt. It doesn't affect the output in any way.

**Comment by rkhayat** [comment]
:+1: okay thanks
