### ISSUE TITLE
How to configure the jsfmt to the line break I want? 

### ISSUE THREAD

**Issue by iplus26** [ionutvmi/sublime-jsfmt#35]
I'm working with React Native these days, so instead of 

    var {Text, ListView, View, Image, StyleSheet, TouchableHighlight, } = React;

I want 

    var {Text, 
        ListView,
        View,
        //...
        TouchableHighlight } = React;

I've walked through the [esformatter preset files](https://github.com/millermedeiros/esformatter/tree/master/lib/preset) but I can't understand it well... So any help will be appreciated.

**Comment by ionutvmi** [comment]
Something like this should do the trick for your particular line of code.
```
{
    "options":
    {
        "lineBreak" : {
            "after": {
                "ObjectPatternComma": 1
            }
        }
}
```

You can read more about your configuration here:
https://github.com/millermedeiros/esformatter/blob/master/doc/config.md

The ast parser is very helpful in situations like this.

**Comment by iplus26** [comment]
Yes, it works! Thank you!

I also installed *esformatter-var-each* to make the new configuration work.
