### ISSUE TITLE
Use local jsfmt

### ISSUE THREAD

**Issue by manuelstofer** [ionutvmi/sublime-jsfmt#38]
Would be nice to have a option to use the locally installed version of jsfmt for each project. This would allow to install jsfmt + plugins as devDependencies and makes sure that everybody working on the project uses the same configuration.

If you think it's a good idea I would make a pull request.

**Comment by manuelstofer** [comment]
pull request: https://github.com/ionutvmi/sublime-jsfmt/pull/39

**Comment by ionutvmi** [comment]
Sorry for the late reply here.
This is an interesting idea but why would you need to do that ?
For the plugins you could share the same package.json file with the team and for the configuration you can set a project specific `.jsfmtrc` file.

**Comment by manuelstofer** [comment]
I'm aware of .jsfmtrc and use it. But to get it working with non-bundled plugins, they need to be installed into the sublime-jsfmt folder. I would find it better if each project can have its own version of jsfmt and plugins. With a single `npm install` installing everything.

I also have a task in my build system to clean up files, so I have to install jsfmt+plugins a second time locally. I would like to be sure that I use the same versions for editing as in my clean up task.

**Comment by ionutvmi** [comment]
I reviewed the pull request and left some comments.
Please address them and I will merge the changes.

I will close this issue as we can continue the discussion on the PR itself.
