### ISSUE TITLE
an error accoured, what should i do?

### ISSUE THREAD

**Issue by qingyang-id** [ionutvmi/sublime-jsfmt#49]
![image](https://user-images.githubusercontent.com/24997729/30731402-c2c346ce-9f9f-11e7-8f4d-6c89f82a969e.png)

**Comment by mihai-vlc** [comment]
To open the console you can press `` Ctrl + ` ``

You can check on https://github.com/rdio/jsfmt/issues/122 but I don't think jsfmt has support for the full es6 syntax at this moment.
