### ISSUE TITLE
Error: 'node' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by congson95dev** [ionutvmi/sublime-jsfmt#53]
hi . i have an trouble , why this appear in console  and how to fix it?

"Error: 'node' is not recognized as an internal or external command,
operable program or batch file."

it appear when i set auto format : on , and try to save javascript code
thanks

**Comment by mihai-vlc** [comment]
Can you please ensure that the path to the nodejs executable file is configured in your settings 

```
{
    "node-path": "node"
}
```

You should find that under Preferences > Package settings > Sublime JSFMT > Settings – User

you can use settings default as an example

**Comment by mihai-vlc** [comment]
Please reopen the ticket if this doesn't fix your issue.

**Comment by congson95dev** [comment]
`{
	"autoformat": true,
	"node-path": "node",
}
`
i do this but still not working .. same problem still appear.

**Comment by mihai-vlc** [comment]
for the `node-path` parameter can you try to add the full path to the node executable file ?

**Comment by congson95dev** [comment]
hmm .. i added everything from default to user but still not work

`{
    // autoformat on save
    "autoformat": true,

    // array of extensions for autoformat
    "extensions": ["js", "sublime-settings"],

    // options for jsfmt
    "options": {
        "preset": "jquery",
        "indent": {
            "value": "    "
        },
        // plugins included
        "plugins": [
            // "esformatter-quotes",
            // "esformatter-semicolons",
            // "esformatter-braces",
            // "esformatter-dot-notation"
        ]
    },
    "options-JSON": {
        "plugins": [
            "esformatter-quotes"
        ],
        "quotes": {
            "type": "double"
        }
    },
    "node-path": "node",
    "alert-errors": true,
    "ignore-selection": false
}`

**Comment by mihai-vlc** [comment]
The absolute path to your node executable file should be something like: `C:/Program Files/nodejs/node.exe`

**Comment by congson95dev** [comment]
doesn't seem like i have it C:/Program Files/nodejs/node.exe

**Comment by mihai-vlc** [comment]
Maybe you haven't installed nodejs yet ?
https://nodejs.org/en/
